### ISSUE TITLE
vagrantで開発環境を作る

### ISSUE THREAD

**Issue by ikepon** [ikepon/front-end-yattemita#22]
- パーフェクトrails 見ながら、できるところまでやっていく
  - VitualBox
  - Ubuntu14.04LTS

**Comment by ikepon** [comment]
- VitualBox インストール
<img width="673" alt="2015-08-01 0 05 31" src="https://cloud.githubusercontent.com/assets/6753644/9010309/1e8d2c5a-37e1-11e5-8557-1ad6dfbe7ff8.png">

**Comment by ikepon** [comment]
多分大丈夫！
```
➜  front-end-yattemita git:(develop) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'rails'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: front-end-yattemita_default_1438357037965_15913
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.6
    default: VirtualBox Version: 5.0
==> default: Mounting shared folders...
    default: /vagrant => /Users/ikepon/ikepon/front-end-yattemita
➜  front-end-yattemita git:(develop) ✗ vagrant ssh
Welcome to Ubuntu 14.04 LTS (GNU/Linux 3.13.0-24-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Apr 22 19:47:09 2014 from 10.0.2.2
vagrant@ubuntu-14:~$ logout
Connection to 127.0.0.1 closed.
```

**Comment by ikepon** [comment]
たぶん大丈夫！
```
➜  front-end-yattemita git:(setting-vm) bundle exec berks vendor cookbooks
Resolving cookbook dependencies...
Fetching cookbook index from https://api.berkshelf.com...
Installing build-essential (2.2.3)
Installing dmg (2.2.2)
Installing chef_handler (1.2.0)
Installing git (4.3.3)
Installing windows (1.38.1)
Installing yum (3.6.3)
Installing yum-epel (0.6.2)
Vendoring build-essential (2.2.3) to /Users/ikepon/ikepon/front-end-yattemita/cookbooks/build-essential
Vendoring chef_handler (1.2.0) to /Users/ikepon/ikepon/front-end-yattemita/cookbooks/chef_handler
Vendoring dmg (2.2.2) to /Users/ikepon/ikepon/front-end-yattemita/cookbooks/dmg
Vendoring git (4.3.3) to /Users/ikepon/ikepon/front-end-yattemita/cookbooks/git
Vendoring windows (1.38.1) to /Users/ikepon/ikepon/front-end-yattemita/cookbooks/windows
Vendoring yum (3.6.3) to /Users/ikepon/ikepon/front-end-yattemita/cookbooks/yum
Vendoring yum-epel (0.6.2) to /Users/ikepon/ikepon/front-end-yattemita/cookbooks/yum-epel
```

**Comment by ikepon** [comment]
- webサーバ：Nginx
- アプリケーションサーバ：Unicorn
- DB：SQLite3(vm上は一旦これで)

別リポジトリにする必要があるかも。。。

**Comment by ikepon** [comment]
`cookbook database` がないって言われても知らんがな...

```
➜  rails_book_cookbook git:(setting-vm) ✗ vagrant provision

==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-08-01T02:21:11+00:00] INFO: Forking chef instance to converge...
==> default: [2015-08-01T02:21:11+00:00] WARN:
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> default: encrypted, but chef is not able to detect forged replies or man in the middle
==> default: attacks.
==> default:
==> default: To fix this issue add an entry like this to your configuration file:
==> default:
==> default: ```
==> default:   # Verify all HTTPS connections (recommended)
==> default:   ssl_verify_mode :verify_peer
==> default:
==> default:   # OR, Verify only connections to chef-server
==> default:   verify_api_cert true
==> default: ```
==> default:
==> default: To check your SSL configuration, or troubleshoot errors, you can use the
==> default: `knife ssl check` command like so:
==> default:
==> default: ```
==> default:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> default: ```
==> default:
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: Starting Chef Client, version 11.12.2
==> default: [2015-08-01T02:21:11+00:00] INFO: *** Chef 11.12.2 ***
==> default: [2015-08-01T02:21:11+00:00] INFO: Chef-client pid: 1442
==> default: [2015-08-01T02:21:12+00:00] INFO: Setting the run_list to ["recipe[build-essential]", "recipe[git]", "recipe[memcached]", "recipe[nodejs]", "recipe[database]", "recipe[xml]", "recipe[ruby_build]", "recipe[rbenv::system]", "recipe[nginx]", "recipe[imagemagick]"] from CLI options
==> default: [2015-08-01T02:21:12+00:00] INFO: Run List is [recipe[build-essential], recipe[git], recipe[memcached], recipe[nodejs], recipe[database], recipe[xml], recipe[ruby_build], recipe[rbenv::system], recipe[nginx], recipe[imagemagick]]
==> default: [2015-08-01T02:21:12+00:00] INFO: Run List expands to [build-essential, git, memcached, nodejs, database, xml, ruby_build, rbenv::system, nginx, imagemagick]
==> default: [2015-08-01T02:21:12+00:00] INFO: Starting Chef Run for ubuntu-14.04-amd64-vbox
==> default: [2015-08-01T02:21:12+00:00] INFO: Running start handlers
==> default: [2015-08-01T02:21:12+00:00] INFO: Start handlers complete.
==> default: Compiling Cookbooks...
==> default: /tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/homebrew/libraries/homebrew_package.rb:26: warning: toplevel constant Homebrew referenced by Chef::Provider::Package::Homebrew
==> default: [2015-08-01T02:21:13+00:00] INFO: ChefHandler light-weight provider already initialized -- overriding!
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error
==> default: ================================================================================
==> default:
==> default:
==> default: Chef::Exceptions::RecipeNotFound
==> default: --------------------------------
==> default: could not find recipe default for cookbook database
==> default:
==> default:
==> default:
==> default: Running handlers:
==> default: [2015-08-01T02:21:14+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default:
==> default: [2015-08-01T02:21:14+00:00] ERROR: Exception handlers complete
==> default: [2015-08-01T02:21:14+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: Chef Client failed. 0 resources updated in 3.162299241 seconds
==> default: [2015-08-01T02:21:14+00:00] ERROR: could not find recipe default for cookbook database
==> default: [2015-08-01T02:21:14+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by ikepon** [comment]
`cookbook database`はずしたら別の所でエラー。。。
chef 自体がわかってないけーちょっと厳しい感じがしている。。。

諦めてしまいますが、リベンジするときの記録用に　:arrow_down: 

```
➜  rails_book_cookbook git:(setting-vm) ✗ vagrant provision

==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2015-08-01T03:31:25+00:00] INFO: Forking chef instance to converge...
==> default: [2015-08-01T03:31:25+00:00] WARN:
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: SSL validation of HTTPS requests is disabled. HTTPS connections are still
==> default: encrypted, but chef is not able to detect forged replies or man in the middle
==> default: attacks.
==> default:
==> default: To fix this issue add an entry like this to your configuration file:
==> default:
==> default: ```
==> default:   # Verify all HTTPS connections (recommended)
==> default:   ssl_verify_mode :verify_peer
==> default:
==> default:   # OR, Verify only connections to chef-server
==> default:   verify_api_cert true
==> default: ```
==> default:
==> default: To check your SSL configuration, or troubleshoot errors, you can use the
==> default: `knife ssl check` command like so:
==> default:
==> default: ```
==> default:   knife ssl check -c /tmp/vagrant-chef/solo.rb
==> default: ```
==> default:
==> default: * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
==> default: Starting Chef Client, version 11.12.2
==> default: [2015-08-01T03:31:25+00:00] INFO: *** Chef 11.12.2 ***
==> default: [2015-08-01T03:31:25+00:00] INFO: Chef-client pid: 3542
==> default: [2015-08-01T03:31:27+00:00] INFO: Setting the run_list to ["recipe[build-essential]", "recipe[git]", "recipe[memcached]", "recipe[nodejs]", "recipe[xml]", "recipe[ruby_build]", "recipe[rbenv::system]", "recipe[nginx]", "recipe[imagemagick]"] from CLI options
==> default: [2015-08-01T03:31:27+00:00] INFO: Run List is [recipe[build-essential], recipe[git], recipe[memcached], recipe[nodejs], recipe[xml], recipe[ruby_build], recipe[rbenv::system], recipe[nginx], recipe[imagemagick]]
==> default: [2015-08-01T03:31:27+00:00] INFO: Run List expands to [build-essential, git, memcached, nodejs, xml, ruby_build, rbenv::system, nginx, imagemagick]
==> default: [2015-08-01T03:31:27+00:00] INFO: Starting Chef Run for ubuntu-14.04-amd64-vbox
==> default: [2015-08-01T03:31:27+00:00] INFO: Running start handlers
==> default: [2015-08-01T03:31:27+00:00] INFO: Start handlers complete.
==> default: Compiling Cookbooks...
==> default: /tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/homebrew/libraries/homebrew_package.rb:26: warning: toplevel constant Homebrew referenced by Chef::Provider::Package::Homebrew
==> default: [2015-08-01T03:31:27+00:00] INFO: ChefHandler light-weight provider already initialized -- overriding!
==> default: [2015-08-01T03:31:28+00:00] WARN: Cloning resource attributes for package[git-core] from prior resource (CHEF-3694)
==> default: [2015-08-01T03:31:28+00:00] WARN: Previous package[git-core]: /tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/ruby_build/recipes/default.rb:38:in `block in from_file'
==> default: [2015-08-01T03:31:28+00:00] WARN: Current  package[git-core]: /tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/rbenv/libraries/chef_rbenv_recipe_helpers.rb:43:in `block in install_rbenv_pkg_prereqs'
==> default: [2015-08-01T03:31:28+00:00] INFO: ohai plugins will be at: /etc/chef/ohai_plugins
==> default: Recipe: ohai::default
==> default:   * remote_directory[/etc/chef/ohai_plugins for cookbook ohai] action create
==> default: Recipe: <Dynamically Defined Resource>
==> default:   * cookbook_file[/etc/chef/ohai_plugins/README] action create
==> default:  (up to date)
==> default:  (up to date)
==> default: Recipe: ohai::default
==> default:   * ohai[custom_plugins] action reload
==> default: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ohai-7.0.2/lib/ohai/plugins/linux/network.rb:49: warning: already initialized constant IPROUTE_INT_REGEX
==> default: [2015-08-01T03:31:31+00:00] INFO: ohai[custom_plugins] reloaded
==> default:
==> default:     - re-run ohai and merge results into node attributes
==> default:
==> default:
==> default: [2015-08-01T03:31:31+00:00] WARN: Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)
==> default: [2015-08-01T03:31:31+00:00] WARN: Previous service[nginx]: /tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/nginx/recipes/package.rb:47:in `from_file'
==> default: [2015-08-01T03:31:31+00:00] WARN: Current  service[nginx]: /tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/nginx/recipes/default.rb:24:in `from_file'
==> default: Converging 63 resources
==> default: Recipe: build-essential::_debian
==> default:   * package[autoconf] action install
==> default:  (up to date)
==> default:   * package[binutils-doc] action install
==> default:  (up to date)
==> default:   * package[bison] action install
==> default:  (up to date)
==> default:   * package[build-essential] action install
==> default:  (up to date)
==> default:
==> default:   * package[flex] action install
==> default:  (up to date)
==> default:   * package[gettext] action install
==> default:  (up to date)
==> default:   * package[ncurses-dev] action install
==> default: [2015-08-01T03:31:32+00:00] INFO: package[ncurses-dev] is a virtual package, actually acting on package[libncurses5-dev]
==> default:  (up to date)
==> default: Recipe: git::package
==> default:   * git_client[default] action install
==> default: Recipe: <Dynamically Defined Resource>
==> default:   * package[default :create git] action install
==> default:  (up to date)
==> default:  (up to date)
==> default: Recipe: memcached::default
==> default:   * package[memcached] action install
==> default:  (up to date)
==> default:   * package[libmemcache-dev] action install
==> default:  (up to date)
==> default:   * service[memcached] action enable
==> default:  (up to date)
==> default:   * template[/etc/memcached.conf] action create
==> default:  (up to date)
==> default: Recipe: apt::default
==> default:   * file[/var/lib/apt/periodic/update-success-stamp] action nothing
==> default:  (skipped due to action :nothing)
==> default:   * directory[/etc/apt/apt.conf.d] action create
==> default:  (up to date)
==> default:   * cookbook_file[/etc/apt/apt.conf.d/15update-stamp] action create
==> default:  (up to date)
==> default:   * execute[apt-get-update] action run
==> default:  (skipped due to not_if)
==> default:   * execute[apt-get update] action nothing
==> default:  (skipped due to action :nothing)
==> default:   * execute[apt-get autoremove] action nothing
==> default:  (skipped due to action :nothing)
==> default:   * execute[apt-get autoclean] action nothing
==> default:  (skipped due to action :nothing)
==> default:   * execute[apt-get-update-periodic] action run
==> default:  (skipped due to only_if)
==> default:   * directory[/var/cache/local] action create
==> default:  (up to date)
==> default:   * directory[/var/cache/local/preseeding] action create
==> default:  (up to date)
==> default: Recipe: nodejs::repo
==> default:   * package[apt-transport-https] action install
==> default:  (up to date)
==> default:   * apt_repository[node.js] action add
==> default: Recipe: <Dynamically Defined Resource>
==> default:   * execute[install-key 1655a0ab68576280] action run
==> default:  (skipped due to not_if)
==> default:   * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
==> default:   * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
==> default:   * execute[apt-get update] action nothing (skipped due to action :nothing)
==> default:   * file[/etc/apt/sources.list.d/node.js.list] action create
==> default:  (up to date)
==> default:  (up to date)
==> default: Recipe: nodejs::nodejs_from_package
==> default:   * package[nodejs] action install
==> default:  (up to date)
==> default: Recipe: xml::default
==> default:   * package[libxml2-dev] action install
==> default:  (up to date)
==> default:   * package[libxslt-dev] action install
==> default: [2015-08-01T03:31:33+00:00] INFO: package[libxslt-dev] is a virtual package, actually acting on package[libxslt1-dev]
==> default:  (up to date)
==> default: Recipe: ruby_build::default
==> default:   * package[tar] action install
==> default:  (up to date)
==> default:   * package[bash] action install
==> default:  (up to date)
==> default:   * package[curl] action install
==> default:  (up to date)
==> default:   * package[git-core] action install
==> default:  (skipped due to not_if)
==> default:   * execute[Install ruby-build] action nothing (skipped due to action :nothing)
==> default:   * directory[/var/chef/cache] action create
==> default:  (up to date)
==> default:   * git[/var/chef/cache/ruby-build] action checkout
==> default:  (up to date)
==> default: Recipe: rbenv::system_install
==> default:   * package[git-core] action install
==> default:  (up to date)
==> default:   * package[grep] action install
==> default:  (up to date)
==> default:   * directory[/etc/profile.d] action create
==> default:  (up to date)
==> default:   * template[/etc/profile.d/rbenv.sh] action create
==> default:  (up to date)
==> default:   * git[/usr/local/rbenv] action checkout
==> default:  (up to date)
==> default:   * bash[Initialize rbenv (system)] action run
==> default: [2015-08-01T03:31:36+00:00] INFO: bash[Initialize rbenv (system)] ran successfully
==> default:
==> default:     - execute "bash"  "/tmp/chef-script20150801-3542-1fgo6mp"
==> default:
==> default:
==> default:   * log[rbenv-post-init-system] action write
==> default: [2015-08-01T03:31:36+00:00] INFO: rbenv-post-init-system
==> default:
==> default:
==> default: Recipe: rbenv::system
==> default:   * rbenv_ruby[2.1.2] (system) action install
==> default: [2015-08-01T03:31:36+00:00] INFO: Building rbenv_ruby[2.1.2] (system), this could take a while...
==> default: Recipe: <Dynamically Defined Resource>
==> default:   * rbenv_script[rbenv install 2.1.2 (system)] action run
==> default:
==> default:
==> default:
==> default:
==> default:   * rbenv_script[rbenv install 2.1.2 (system)] action nothing
==> default:  (skipped due to action :nothing)
==> default:   * script[rbenv install 2.1.2 (system)] action run

==> default:
==> default: ================================================================================
==> default: Error executing action `run` on resource 'script[rbenv install 2.1.2 (system)]'
==> default: ================================================================================
==> default:
==> default:
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150801-3542-r5i4fq" ----
==> default: STDOUT:
==> default: STDERR: rbenv: version `global' not installed
==> default: Downloading ruby-2.1.2.tar.gz...
==> default: -> https://dqw8nmjcqpjn7.cloudfront.net/f22a6447811a81f3c808d1c2a5ce3b5f5f0955c68c9a749182feb425589e6635
==> default: Installing ruby-2.1.2...
==> default:
==> default: BUILD FAILED (Ubuntu 14.04 using ruby-build 20150719)
==> default:
==> default: Inspect or clean up the working tree at /tmp/ruby-build.20150801033136.4134
==> default: Results logged to /tmp/ruby-build.20150801033136.4134.log
==> default:
==> default: Last 10 log lines:
==> default: The Ruby openssl extension was not compiled.
==> default: The Ruby readline extension was not compiled.
==> default: The Ruby zlib extension was not compiled.
==> default: ERROR: Ruby install aborted due to missing extensions
==> default: Try running `apt-get install -y libssl-dev libreadline-dev zlib1g-dev` to fetch missing dependencies.
==> default:
==> default: Configure options used:
==> default:   --prefix=/usr/local/rbenv/versions/2.1.2
==> default:   LDFLAGS=-L/usr/local/rbenv/versions/2.1.2/lib
==> default:   CPPFLAGS=-I/usr/local/rbenv/versions/2.1.2/include
==> default: ---- End output of "bash"  "/tmp/chef-script20150801-3542-r5i4fq" ----
==> default: Ran "bash"  "/tmp/chef-script20150801-3542-r5i4fq" returned 1
==> default:
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/rbenv/providers/script.rb
==> default:
==> default:  28:   script new_resource.name do
==> default:  29:     interpreter   "bash"
==> default:  30:     code          script_code
==> default:  31:     user          new_resource.user     if new_resource.user
==> default:  32:     creates       new_resource.creates  if new_resource.creates
==> default:  33:     cwd           new_resource.cwd      if new_resource.cwd
==> default:  34:     group         new_resource.group    if new_resource.group
==> default:  35:     path          new_resource.path     if new_resource.path
==> default:  36:     returns       new_resource.returns  if new_resource.returns
==> default:  37:     timeout       new_resource.timeout  if new_resource.timeout
==> default:  38:     umask         new_resource.umask    if new_resource.umask
==> default:  39:     environment(script_environment)
==> default:  40:   end
==> default:  41:
==> default:
==> default:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/rbenv/providers/script.rb:28:in `block in class_from_file'
==> default:
==> default: script("rbenv install 2.1.2 (system)") do
==> default:   action "run"
==> default:   retries 0
==> default:   retry_delay 2
==> default:   guard_interpreter :default
==> default:   command "\"bash\"  \"/tmp/chef-script20150801-3542-r5i4fq\""
==> default:   backup 5
==> default:   environment {"RBENV_ROOT"=>"/usr/local/rbenv"}
==> default:   returns [0]
==> default:   code "export RBENV_ROOT=\"/usr/local/rbenv\"\nexport PATH=\"${RBENV_ROOT}/bin:$PATH\"\neval \"$(rbenv init -)\"\n\nrbenv shell global\n\nrbenv install 2.1.2\n"
==> default:   interpreter "bash"
==> default:   cookbook_name :rbenv
==> default: end
==> default:
==> default:
==> default:
==> default: [2015-08-01T03:36:10+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:
==> default: Running handlers:
==> default: [2015-08-01T03:36:10+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default:
==> default: [2015-08-01T03:36:10+00:00] ERROR: Exception handlers complete
==> default: [2015-08-01T03:36:10+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: Chef Client failed. 5 resources updated in 284.818046205 seconds
==> default: [2015-08-01T03:36:10+00:00] ERROR: script[rbenv install 2.1.2 (system)] (/tmp/vagrant-chef/5b5d8c8384a4a2198f8f721c6bf77a30/cookbooks/rbenv/providers/script.rb line 28) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of "bash"  "/tmp/chef-script20150801-3542-r5i4fq" ----
==> default: STDOUT:
==> default: STDERR: rbenv: version `global' not installed
==> default: Downloading ruby-2.1.2.tar.gz...
==> default: -> https://dqw8nmjcqpjn7.cloudfront.net/f22a6447811a81f3c808d1c2a5ce3b5f5f0955c68c9a749182feb425589e6635
==> default: Installing ruby-2.1.2...
==> default:
==> default: BUILD FAILED (Ubuntu 14.04 using ruby-build 20150719)
==> default:
==> default: Inspect or clean up the working tree at /tmp/ruby-build.20150801033136.4134
==> default: Results logged to /tmp/ruby-build.20150801033136.4134.log
==> default:
==> default: Last 10 log lines:
==> default: The Ruby openssl extension was not compiled.
==> default: The Ruby readline extension was not compiled.
==> default: The Ruby zlib extension was not compiled.
==> default: ERROR: Ruby install aborted due to missing extensions
==> default: Try running `apt-get install -y libssl-dev libreadline-dev zlib1g-dev` to fetch missing dependencies.
==> default:
==> default: Configure options used:
==> default:   --prefix=/usr/local/rbenv/versions/2.1.2
==> default:   LDFLAGS=-L/usr/local/rbenv/versions/2.1.2/lib
==> default:   CPPFLAGS=-I/usr/local/rbenv/versions/2.1.2/include
==> default: ---- End output of "bash"  "/tmp/chef-script20150801-3542-r5i4fq" ----
==> default: Ran "bash"  "/tmp/chef-script20150801-3542-r5i4fq" returned 1
==> default: [2015-08-01T03:36:10+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```
